language: go

go:
  - 1.x

before_install:
  - echo -e "machine github.com\n  login jeremiahyan\n  password $CI_USER_PASSWORD" >> ~/.netrc
#  - if [[ $TRAVIS_BRANCH = 'master' ]]; then
#      export DPORT="2022"
#    else
#      export DPORT="4022"
#      ;
#    fi
  - export DHOST="47.100.0.27"
  - export DPORT="2022"

#matrix:
#  include:
#    - env: DHOST='47.100.0.27'
#      on:
#        branch: master
#    - env: DHOST='101.132.143.0'
#      on:
#        branch: preview

addons:
  ssh_known_hosts:
    - 101.132.143.0:2022
    - 47.100.0.27:2022

before_deploy:
  - openssl aes-256-cbc -K $encrypted_544ce9b78898_key -iv $encrypted_544ce9b78898_iv -in deploy_boiler_rsa.enc -out /tmp/deploy_boiler_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_boiler_rsa
  - ssh-add /tmp/deploy_boiler_rsa
  - chmod o+x build.sh
#  - chmod a+x ci_profile.sh
#  - ./ci_profile.sh

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -azr -e "ssh -p $DPORT" --exclude=".git" --exclude=".gitignore" --exclude="*.enc" --exclude="*.yml" --exclude="tests" $TRAVIS_BUILD_DIR root@$DHOST:$AZUREPATH
  on:
  # tags: true
    all_branches: true

#  - provider: script
#    skip_cleanup: true
#    script: rsync -azr -e "ssh -p $DPORT" --exclude=".git" --exclude=".gitignore" --exclude="*.enc" --exclude="*.yml" --exclude="tests" $TRAVIS_BUILD_DIR root@$DHOST:$AZUREPATH
#    on:
#      branch: preview

after_deploy:
  - echo $DHOST
  rsync -azr -e "ssh -p $DPORT" --exclude=".git" --exclude=".gitignore" --exclude="*.enc" --exclude="*.yml" --exclude="tests" $TRAVIS_BUILD_DIR root@$DHOST:$AZUREPATH
  - ssh -p $DPORT root@$DHOST "cd $AZUREPATH/boiler-server/ && ./build.sh"

after_script:
  - ssh -p $DPORT root@$DHOST "cd $AZUREPATH/boiler-server/ && nohup ./boiler-server &"
