language: go

go:
  - 1.x

before_install:
  - echo -e "machine github.com\n  login jeremiahyan\n  password $CI_USER_PASSWORD" >> ~/.netrc
  - export DPORT='2022'
#  - if [[ $TRAVIS_BRANCH = 'master' ]]; then
#      export DHOST='47.100.0.27'
#    else
#      export DHOST='101.132.143.0'
#    fi

#matrix:
#  include:
#    - env: DHOST='47.100.0.27'
#      on:
#        branch: master
#    - env: DHOST='101.132.143.0'
#      on:
#        branch: preview

addons:
  ssh_known_hosts:
    - 101.132.143.0:2022
    - 47.100.0.27:2022

before_deploy:
  - openssl aes-256-cbc -K $encrypted_544ce9b78898_key -iv $encrypted_544ce9b78898_iv -in deploy_boiler_rsa.enc -out /tmp/deploy_boiler_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_boiler_rsa
  - ssh-add /tmp/deploy_boiler_rsa
  - chmod o+x build.sh
  - echo $TRAVIS_BRANCH
  - echo $DHOST

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - export DHOST='47.100.0.27'
      - rsync -azr -e "ssh -p $DPORT" --exclude=".git" --exclude=".gitignore" --exclude="*.enc" --exclude="*.yml" --exclude="tests" $TRAVIS_BUILD_DIR root@$DHOST:$AZUREPATH
    on:
    # tags: true
    # all_branches: true
      branch: master

  - provider: script
    skip_cleanup: true
    script:
      - export DHOST='101.132.143.0'
      - rsync -azr -e "ssh -p $DPORT" --exclude=".git" --exclude=".gitignore" --exclude="*.enc" --exclude="*.yml" --exclude="tests" $TRAVIS_BUILD_DIR root@$DHOST:$AZUREPATH
    on:
    # tags: true
    # all_branches: true
      branch: preview

after_deploy:
  - echo $DHOST
  - ssh -p $DPORT root@$DHOST "cd $AZUREPATH/boiler-server/ && ./build.sh"

after_script:
  - ssh -p $DPORT root@$DHOST "cd $AZUREPATH/boiler-server/ && nohup ./boiler-server &"
