language: go

go:
  - 1.x

before_install:
  - echo -e "machine github.com\n  login jeremiahyan\n  password $CI_USER_PASSWORD" >> ~/.netrc
  - export DHOST="101.132.143.0"
  - export RHOST="47.100.0.27"
  - export DPORT="2022"

addons:
  ssh_known_hosts:
    - 101.132.143.0:2022
    - 47.100.0.27:2022

before_deploy:
  - openssl aes-256-cbc -K $encrypted_544ce9b78898_key -iv $encrypted_544ce9b78898_iv -in deploy_boiler_rsa.enc -out /tmp/deploy_boiler_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_boiler_rsa
  - ssh-add /tmp/deploy_boiler_rsa
  - chmod o+x build.sh

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -azr -e "ssh -p $DPORT" --exclude=".git" --exclude=".gitignore" --exclude="*.enc"
    --exclude="*.yml" --exclude="tests" $TRAVIS_BUILD_DIR root@$DHOST:$AZUREPATH
  on:
    branch: preview

after_deploy:
  - ssh -p $DPORT root@$DHOST "cd $AZUREPATH/boiler-server/ && ./build.sh"

after_script:
  - ssh -p $DPORT root@$DHOST "cd $AZUREPATH/boiler-server/ && nohup ./boiler-server &"
